services:
  mindustry-server:
    image: formattoday/mindustry-server:latest
    container_name: mindustry-server
    restart: unless-stopped
    ports:
      - "6567:6567/tcp"
      - "6567:6567/udp"
    volumes:
      - ./data:/app/config
    environment:
      - JAVA_OPTS=-Xmx2G -Xms512M
    entrypoint: ["/sbin/tini", "--", "sh", "-c", "java $JAVA_OPTS -jar server.jar host"]
    stop_grace_period: 30s
